sudo: required
services:
  - docker

before_install:
  - docker build -t xubingtao/docker-react-test -f Dockerfile.dev .

script:
  - docker run xubingtao/docker-react-test npm run test -- --coverage
